name:  CI/CD Pipeline

# Event: triggers the workflow on every push to main branch
on:
  push:
    branches: [ main ]

# Job: a set of steps that run on a runner machine
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps: individual tasks within the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Make directory
        run: mkdir my-new-folder && ls -la

      - name: Echo message
        run: echo "I am learning Github Actions"
